### ISSUE TITLE
opuslib.exceptions.OpusError: <exception str() failed>

### ISSUE THREAD

**Issue by cogmeta** [OnBeep/opuslib#11]
I am trying to decode in python a file encoded using opus_demo and i am getting this exception. Any idea what is going wrong.

 
Encoding
 opus-1.2.1
./opus_demo -e audio 16000 1 16000  ./input.raw encoded.bin

Decoding 
python 2.7 and  opuslib==2.0.0
 decoder = opuslib.Decoder(16000, 1)
decoder.decode(packet, frame_size=320)

Traceback (most recent call last):
  File "opus_py.py", line 20, in <module>
    decoder.decode(packet, frame_size=320)
  File "/usr/local/lib/python2.7/dist-packages/opuslib/classes.py", line 45, in decode
    channels=self._channels)
  File "/usr/local/lib/python2.7/dist-packages/opuslib/api/decoder.py", line 178, in decode
    raise opuslib.exceptions.OpusError(result)
opuslib.exceptions.OpusError: <exception str() failed>

**Comment by avrong** [comment]
Having the same problem while using `Encoder.encode`.

```bash
Traceback (most recent call last):
  File ".\main.py", line 20, in <module>
    opus_b = encoder.encode(arr_b, duration * fs)
  File "...\venv\lib\site-packages\opuslib\classes.py", line 180, in encode
    len(pcm_data)
  File "...\venv\lib\site-packages\opuslib\api\encoder.py", line 140, in encode
    'Opus Encoder returned result="{}"'.format(result))
opuslib.exceptions.OpusError: <exception str() failed>
```

```python3
fs = 48000
duration = 2

recording = <numpy array>
arr_b = numpy.array(recording).tobytes()

encoder = opuslib.Encoder(fs, 2, opuslib.APPLICATION_AUDIO)
opus_b = encoder.encode(arr_b, duration * fs)
```

Windows 10, Python 3.7

**Comment by polars05** [comment]
I am also getting the same <exception str() failed> error as @cogmeta and @avrong when I attempt to decode (in Python 3.7, Opus 1.3.1) from a file containing bytes; has there been a solution worked out for this error? Thanks!

**Comment by luigifcruz** [comment]
I think this is related to the `frame_size`. This is what libopus [documentation](https://opus-codec.org/docs/html_api-1.1.0/group__opus__encoder.html) says:

> `frame_size` Number of samples per channel in the input signal. This must be an Opus frame size for the encoder's sampling rate. For example, at 48 kHz the permitted values are 120, 240, 480, 960, 1920, and 2880. Passing in a duration of less than 10 ms (480 samples at 48 kHz) will prevent the encoder from using the LPC or hybrid modes.

**Comment by vidarr** [comment]
I think part of the problem is:

OpusError requires an Integer as argument. In `opuslib/exceptions.py:17`:

```
class OpusError(Exception):
    ....
    def __init__(self, code: int) -> None:
```

But on some places, strings are passed into the constructor. E.g. looking at the problem reported by [avrong](https://github.com/orion-labs/opuslib/issues/11#issuecomment-411918034), `opuslib/api/encoder.py:139`:

```
raise opuslib.OpusError(
    'Opus Encoder returned result="{}"'.format(result))
```

However, this exception would be raised for a reason, I guess, thus your examples will probably still fail to work if one fixed this issue ...
