### ISSUE TITLE
Tests fail: ImportError: No module named tests

### ISSUE THREAD

**Issue by yurivict** [OnBeep/opuslib#4]
Both coverage and nose are installed, but getting this error:
```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    'Topic :: Multimedia :: Sound/Audio :: Conversion',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 234, in run_tests
    **exit_kwarg
  File "/usr/local/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/local/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named tests
```

Version 2.0.0.
Found on FreeBSD 11.1.

**Comment by jlaine** [comment]
I'd say this issue should be closed, recent versions don't support python2.
